# Generated by Django 3.2.7 on 2022-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexNumber', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexNumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('UserName', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('UserName', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Zoom_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=250)),
                ('linkDate', models.CharField(max_length=100)),
                ('linktime', models.CharField(max_length=100)),
                ('Note', models.CharField(max_length=300)),
            ],
        ),
    ]
