# Generated by Django 3.2.7 on 2022-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Contact', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
