# Generated by Django 3.2.7 on 2022-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0002_auto_20221008_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
