# Generated by Django 3.2.7 on 2022-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0003_auto_20221008_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(max_length=12)),
            ],
        ),
    ]
