# Generated by Django 3.2.7 on 2022-10-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0004_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='jobIndustry',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
