# Generated by Django 3.2.7 on 2022-10-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0005_auto_20221009_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Zoom_link',
        ),
    ]
