# Generated by Django 3.2.7 on 2022-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0006_auto_20221009_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Interest', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student_jobprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
